### PR TITLE
fix https://github.com/voxpupuli/puppet-gitlab_ci_runner/issues/61

### LINKED ISSUE #61: registration_token containing undescore gets modified
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.10.1
- Ruby:
- Distribution: ubuntu bionic
- Module version: current master (18.11.2019)

## How to reproduce (e.g Puppet code you use)
If the registration_token contains an underscore, it gets converted into a "minus", and then of course the registration fails

## What behaviour did you expect instead
Should be able to register :)

### PR DESCRIPTION
**Pull request by Farfaday**
fix #61

### CODE REVIEW

**Comment by baurmatt** [comment]
Hey @Farfaday, thanks for providing a PR for this bug! :) Could you please add a tests?

**Comment by Farfaday** [comment]
@baurmatt I changed the test registration-token in gitlab_ci_runner_spec.rb, but I don't really know how to write a check for that, as the token is not present in the /etc/gitlab-runner/config.toml file.
(The registration is done via an exec)

**Comment by baurmatt** [comment]
Hey @Farfaday, thank you for you fast answer! :) I see your problem: There is just no rspec test for `gitlab_ci_runner::runner`. I think the PR looks good and I definitely like to get it merged! But I also want to have the confidence of a successful test before merging it.

As I'm currently in the middle of doing a major refactoring of this module, I will postpone this PR until we have tests for `gitlab_ci_runner::runner`. I will come back to this PR! :)

**Comment by baurmatt** [comment]
Hey @Farfaday, I've almost finished the refactoring of this module. The last part, `gitlab_ci_runner::runner`, will be done with #74. I'm not 100% sure, but I think it might already solve your problem. That's because in the current master we do the `s,_,-,g` replacement over keys + values. I've chosen to only do this on the key because I don't see why we should change the value of a user provided configuration.

Can you please test if your problem is resolved with #74? If not, I happy to review your change after #74 got reviewed and you rebased this branch (pretty sure that will be a terrifying experience, sorry for that! ;)) onto it.

Thanks and have a great weekend! :)

**Pull request closed without merging**
