### PR TITLE
add limitations about the runner configurations

### PR DESCRIPTION
**Pull request by thde**
I added some info about current limitations regarding runner configs:
https://github.com/voxpupuli/puppet-gitlab_ci_runner/blob/master/manifests/runner.pp#L52

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
If this is true then wouldn't this be a bug, not a limitation we'd want to accept?

Also related: https://gitlab.com/gitlab-org/gitlab-runner/issues/3022

**Comment by thde** [comment]
> If this is true then wouldn't this be a bug, not a limitation we'd want to accept?

You could say that yes. I think as soon as the bug is resolved the limitations should be removed. But until that it's quite an important thing to know from my point of view.

**Comment by LongLiveCHIEF** [comment]
Considering how puppet _normally_ works, I think I agree with you on this one, especially since the upstream functionality from the vendor itself only exists by hand-editing and not their own cli yet.

@bastelfreak I'm not up on the latest PR requirements. I merged one a few weeks ago that wasn't validated, and I haven't figured out what that means yet.

Can you look at this one and let me know if it meets our merge requirements?

**Comment by bastelfreak** [comment]
@thde can you please rebase? The PR has merge conflicts that must be resolved.

@LongLiveCHIEF the PR looks fine except for the required rebase. We've our review/style guidelines  available at: https://voxpupuli.org/docs/#reviewing-a-module-pr . Let me know if they are unclear or you think anything is missing.

**Comment by thde** [comment]
I had to create a new PR (https://github.com/voxpupuli/puppet-gitlab_ci_runner/pull/56) as the fork was deleted and orphaned PRs [can't be reconnected](https://stackoverflow.com/questions/55810181/re-attach-pull-requests-to-branches-after-repository-transferred-to-personal-acc).

**Pull request closed without merging**
