### PR TITLE
modulesync 2.9.0

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by baurmatt** [comment]
Hey @dhoppe, can you please take a look at the failing tests? :)

**Comment by baurmatt** [comment]
Thanks! :)

**Comment by bastelfreak** [comment]
@dhoppe @baurmatt of you do a modulesync/merge a modulesync PR please ensure it's labeled correctly and delete the branch afterwards.

**Comment by baurmatt** [comment]
Hey @bastelfreak, sorry! :) Can we label the modulesync PRs by default? Seems like modulesync is capable of doing this -> https://github.com/voxpupuli/modulesync#submitting-prs-to-github

Perhaps we could also activate branch deletion on merge by default -> https://help.github.com/en/github/administering-a-repository/managing-the-automatic-deletion-of-branches

**Comment by dhoppe** [comment]
@baurmatt https://github.com/voxpupuli/modulesync_config/commit/fb873f4d3e56bf073930d0ebe9d3c472a11393ea

**Comment by baurmatt** [comment]
@dhoppe Awesome! ❤️ How about the `Automatically delete head branches` setting? Is there somthing like modulesync for repository settings?

**Pull request merged**
