### PR TITLE
Add support for current releases

### PR DESCRIPTION
**Pull request by dhoppe**

### CODE REVIEW

**Comment by dhoppe** [comment]
The acceptance tests should also provide a running GitLab instance where the GitLab runner can connect to.

**Comment by LongLiveCHIEF** [comment]
@dhoppe I don't think we need a gitlab instance to do acceptance testing. I think we could mock anything needed for this. You could wind up with false failures if problems occur with the gitlab instance launch.

GitLab does acceptance testing on all the features that runner uses to connect with GitLab, so it would be redundant to do all that work when all we really need to focus on with puppet is that it is managing the state in the way we expect.

**Comment by LongLiveCHIEF** [comment]
That being said, if for some reason I haven't thought of that we _do_ need an instance, I think going with the [dockerized gdk](https://gitlab.com/gitlab-org/gitlab-development-kit) would be the best bet.  It pre-loads data and everything and is an ideal platform for running acceptance tests against.

Downside is that startup takes quite a while, and we'd needs to find a way to cache this so each job in a run wouldn 't need to spin it up.

**Comment by baurmatt** [comment]
This looks good to me! :)

@dhoppe Could you please rebase you branch and fix the merge conflict? :)

**Comment by baurmatt** [comment]
Thank you! :)

**Pull request merged**
