### PR TITLE
Allow `hkp://` style URLs for `repo_keyserver` URL

### PR DESCRIPTION
**Pull request by hp197**
Fixes voxpupuli/puppet-gitlab_ci_runner#101

### CODE REVIEW

**Review by kenyon — APPROVED** [review]
Would be good to also add a test for this so that it doesn't get changed back.

**Comment by hp197** [comment]
Added test case, will need to test it offline though, travis isn't playing nice.

**Comment by kenyon** [comment]
> Please also note the apt::key regex: https://github.com/puppetlabs/puppetlabs-apt/blob/main/manifests/key.pp#L43
> 
> Maybe it should be converted to something like that?

Sure, I think that would be an improvement, so if you want to do that, go ahead. :smiley:

**Comment by kenyon** [comment]
We need to get #93 done to get the tests to pass.

**Comment by hp197** [comment]
>     with manage_repo => true and repo_keyserver => keys.gnupg.net
>       is expected to compile into a catalogue without dependency cycles
>       is expected to contain Class[gitlab_ci_runner::repo]
>       is expected to contain Apt::Source[apt_gitlabci] with key => {"id"=>"F6403F6544A38863DAA0B6E03F01618A51312F3F", "server"=>"keys.gnupg.net"}
>     with manage_repo => true and repo_keyserver => hkp://keys.gnupg.net:80
>       is expected to compile into a catalogue without dependency cycles
>       is expected to contain Class[gitlab_ci_runner::repo]
>       is expected to contain Apt::Source[apt_gitlabci] with key => {"id"=>"F6403F6544A38863DAA0B6E03F01618A51312F3F", "server"=>"hkp://keys.gnupg.net:80"}
>     with manage_repo => true and repo_keyserver => https://keys.gnupg.net:88
>       is expected to compile into a catalogue without dependency cycles
>       is expected to contain Class[gitlab_ci_runner::repo]
>       is expected to contain Apt::Source[apt_gitlabci] with key => {"id"=>"F6403F6544A38863DAA0B6E03F01618A51312F3F", "server"=>"https://keys.gnupg.net:88"}

Added custom keyserver type with the regex. This is in my opinion cleaner then add the whole regex to init.pp.
Existing functionality still works as before.

**Comment by hp197** [comment]
ready to merge ❤️

**Review by kenyon — APPROVED** [review]

**Comment by alexjfisher** [comment]
@hp197 Sorry for the delay.  Would you be able to rebase, so that we could get this change in?

**Comment by hp197** [comment]
Sure, though I'm on vacation for the next 2 weeks. If you can wait on that
I'll do it after I'm back.

**Comment by hp197** [comment]
rebased, ready to merge (if tests pass) ❤️

**Comment by hp197** [comment]
@alexjfisher ready and tests passed

**Comment by alexjfisher** [comment]
@hp197 Thanks!

**Pull request merged**
