### PR TITLE
Move all defaults to Hiera

### PR DESCRIPTION
**Pull request by smortex**
#### Pull Request (PR) description

Move all defaults to Hiera

This was requested here:
https://github.com/voxpupuli/puppet-gitlab_ci_runner/pull/40/files/762309085d49c95cb8ca09f8325aa9972554c2b9#r278947984

While here, move back xz_package_name to the end of the list.

#### This Pull Request (PR) fixes the following issues

n/a

### CODE REVIEW

**Comment by LongLiveCHIEF** [comment]
Personally, I don't like this. It means you can't quickly look at the `init.pp` and determine the defaults. You now have to decipher hiera hierarchy to verify what the defaults are.

It also means there is more room for bugs to be introduced. In my experience, defaults should only be put into hiera if they're _not_ common.

These just seems like an anti-pattern to me.

**Comment by alexjfisher** [comment]
@LongLiveCHIEF Without this change you still have to look in hiera.  If you look at just `init.pp`, you've got no hint as to which 'mandatory' parameters are actually mandatory.  ie https://github.com/voxpupuli/puppet-gitlab_ci_runner/blob/42526cfd70629b27c4c590d448a5155be1f92c07/manifests/init.pp#L20 doesn't need to be specified, as the correct value comes from hiera.

We don't appear to have much of a consensus around this. See https://github.com/puppetlabs/pdk-templates/issues/205 for more discussion.

**Comment by LongLiveCHIEF** [comment]
@alexjfisher yes you do, that's what enforced data types are for.`[Optional]`is there for ones that are mandatory. If `[Optional]` is not there, and there's no default value, then it's a hierarchical value and therefore in hiera.

**Comment by alexjfisher** [comment]
> `[Optional]` is there for ones that are mandatory

If anything, shouldn't the reverse be true?  `Optional` only actually means a value is allowed to be assigned `undef`. I vaguely remember a ticket where a puppet employee was regretting that they named the type 'Optional'.

**Comment by alexjfisher** [comment]
@LongLiveCHIEF I've also found https://github.com/puppetlabs/best-practices/commit/e96ab2399eccf455081a5d798e05f47c40a0c10f  which seems to align with what you'd prefer.

**Comment by LongLiveCHIEF** [comment]
Closing this one per updated voxpupuli guidelines on handling hiera defaults.

**Pull request closed without merging**
